services:
  frontend:
    build: /client
    ports:
     - "5173:5173"
    networks:
      - mern
    environment:
      - VITE_APP_NOT_SECRET_CODE=${VITE_APP_NOT_SECRET_CODE}
  backend:
    build: /server
    ports:
      - "5000:5000"
    networks:
      - mern
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - frontend

networks:
  mern:
    driver: bridge